name: qurandigital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get: ^4.6.5
  lottie: 1.3.0
  html: ^0.15.0
  get_storage: 2.0.3
  just_audio: 0.9.26
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/lottie/
  uses-material-design: true

window_size: 
  git: 
    url: git://github.com/google/flutter-desktop-embedding.git
    path: plugins/window_size

